### ISSUE TITLE
Issues with configuration

### ISSUE THREAD

**Issue by ilopmar** [YuMS/gitlab-ce-pages#1]
Hi. I would like to try this to get my static pages in my own Gitlab CI instance but I'm stuck in the documentation.
- I've created the `page` account, add it to the repository member with **Reporter** privilege
- I start the docker container with like this:  

```
      docker run -it --restart=always \
            --env 'PAGE_PRIVATE_TOKEN=iqiQitszZf47eZNeszNU' \
            --env 'GITLAB_URL=https://my-gitlab.example.com' \
            --env 'PROJECT_ROOT=public' \
            --volume /srv/gitlab-ce-pages/public:/home/pages/public/ \
            -p 8000:80 \
            yums/gitlab-ce-pages
```
- Then, when you say _Provide your server's root URL to repository owners as webhook URL._ I don't know what it means or where I can get this information.
- I don't know exactly the URL I need to add to my project as a webhook. I assume is exactly the same I get in the previous step, but I don't how where get it.
- The last step is build and check my page under {GITLAB_CE_PAGE_URL}/{WORKSPACE}/{PROJECT_NAME}. I don't know how to build this url.  
  Could it be something like this `https://my-gitlab.example.com/ivan/test`. My username is `ivan` and my project name is `test`. Is that url correct?

I really hope you can help me.

Thank you very much.

**Comment by YuMS** [comment]
Hi.
Because this project is not integrated with GitLab, you can deploy it anywhere except under the URL your GitLab instance already occupied, in theory. (Of course you can force to do so to always parse the URL first to determine whether to assign a request to GitLab instance or GCP instance with proxy, but that's ugly because in such way you hijack some part of GitLab instance)

_Your server's root URL_ here is the URL for your GCP instance. Like `https://pages.example.com`, which is expected to be bonded to port 8000 of your docker instance in your case in some way. Actually, you can just use `http://<ip-address-of-your-host-that-runs-docker-instance>:8000` as webhook as long as it is accessable from your GItLab server.
And yes, this is URL is what you should provide to your GitLab users as webhook URL.

The build is trivial once you enabled GitLab CI and added .gitlab-ci.yml file in, every commit of selected branch in .gitlab-ci.yml will trigger the build.

Hope this helps.

**Comment by ilopmar** [comment]
Hi. Thank you for fast reply. Now I have configured it but I have a problem with the directory and the file system permissions running on docker:

```
172.17.0.1 - - [22/Jun/2016:09:44:04 +0000] "POST / HTTP/1.1" 200 2 "-" "-"
options { url: 'https://my-gitlab.example.com/api/v3/projects/195/builds/779/artifacts',
  headers: { 'PRIVATE-TOKEN': 'iqiQitszZf47eZNeszNU' } }
779.zip downloaded
unzipp 779.zip failed
{ [Error: Command failed: unzip /home/pages/public/779.zip -d /home/pages/public/Iván López/prueba
caution: filename not matched:  López/prueba
]
  killed: false,
  code: 11,
  signal: null,
  cmd: 'unzip /home/pages/public/779.zip -d /home/pages/public/Iván López/prueba' }
```

The problem is that you are using the fullname of the user "Iván López" instead of the username "ivan.lopez", so now there's a empty space in the directory. I think if you can change it it should work.

Regards, Iván.

**Comment by YuMS** [comment]
You are absolutely right. Thank you.

**Comment by YuMS** [comment]
b212f02f413527239cc3ddef633018a1b2aa2dcc fixed this.

Try with `yums/gitlab-ce-pages:1.0.2`

**Comment by ilopmar** [comment]
Now it's working, thank you very much! I'm going to deploy it in my production server and tell about it to my colleagues :smile:
