### ISSUE TITLE
Informs the Gitlab version requirements in Readme

### ISSUE THREAD

**Issue by SrMouraSilva** [YuMS/gitlab-ce-pages#10]
The gitlab-ce-pages requires build API, they has been provided in [Gitlab 8.4](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CHANGELOG#L1812).

Please, informs the restriction.

**Comment by YuMS** [comment]
THX!

Looks like the CHANGELOG entry you provided is about receiving incoming build trigger rather than emitting build events. I found [this commit](https://gitlab.com/gitlab-org/gitlab-ce/commit/2988e1fbf50b3c9e803a9358933e3e969e64dcc3) on GitLab the one `Build events` was included into webhook settings page. And this commit was included into 8.3.

I don't know if I should say 8.3 or 8.4 for this so I'll use a blurry number.

**Comment by YuMS** [comment]
Added in 28d255a

**Comment by SrMouraSilva** [comment]
Thanks!!

The Gitlab 8.3 not contains `GET /projects/:id/builds` https://docs.gitlab.com/ce/api/builds.html#list-project-builds

I tried to use: Error in https://github.com/YuMS/gitlab-ce-pages/blob/master/src/deployer.js#L93

**Comment by YuMS** [comment]
I found adding blurry version by regular expression hard so I used 8.4. 🍭
